# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Github Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Authorizing Github action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        uses: oleksiyrudenko/gha-git-credentials@v1

      - name: Doploy to GitHub Pages
        uses: amitsingh-007/deploy-to-github-pages@v1.1
        env:
          CI: false
        

        